### ISSUE TITLE
WSL Formatting issue

### ISSUE THREAD

**Issue by thenger** [hashicorp/vscode-terraform#1639]
### Extension Version

2.29.0

### VS Code Version

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

### Operating System

Windows/WSL : Linux myhostname 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux ||| Debian 12.2

### Terraform Version

Terraform v1.3.6 on linux_amd64

### Steps to Reproduce

1. VSCode  on Windows with WSL and "ms-vscode-remote.remote-wsl" extension
2. Install "hashicorp.terraform" via vscode (latest version or pre-release)
3. configure to have the formatting option
4. right clicking inside a .tf file does not bring the menu "Format document"
5. Shift+Alt+F format says "There is no formatter for 'terraform' files installed".

### Expected Behavior

format .tf (and terragrunt.hcl ?) file

### Actual Behavior

When ext is installed: no formatting available

logs "Extension Host (Remote)":
```
2023-11-21 12:08:35.634 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-11-21 12:08:35.635 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-11-21 12:08:35.635 [info] ExtensionService#_doActivateExtension sketchbuch.vsc-workspace-sidebar, startup: false, activationEvent: 'onStartupFinished'
2023-11-21 12:08:43.619 [info] ExtensionService#_doActivateExtension hashicorp.terraform, startup: false, activationEvent: 'workspaceContains:**/*.tf,**/*.tfvars'
2023-11-21 12:08:43.713 [error] Activating extension hashicorp.terraform failed due to an error:
2023-11-21 12:08:43.713 [error] Error: Unable to launch language server: not found: ~/.local/bin/terraform. Check "terraform.languageServer.path" in your settings.
	at t.ServerPath.resolvedPathToBinary (/home/username/.vscode-server/extensions/hashicorp.terraform-2.29.0-linux-x64/out/extension.js:2:495521)
	at t.getServerOptions (/home/username/.vscode-server/extensions/hashicorp.terraform-2.29.0-linux-x64/out/extension.js:2:494314)
	at e.activate (/home/username/.vscode-server/extensions/hashicorp.terraform-2.29.0-linux-x64/out/extension.js:2:1090262)
	at q.ib (/home/username/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/out/vs/workbench/api/node/extensionHostProcess.js:136:13170)
	at q.hb (/home/username/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/out/vs/workbench/api/node/extensionHostProcess.js:136:12896)
	at /home/username/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/out/vs/workbench/api/node/extensionHostProcess.js:136:11037
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async w.n (/home/username/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/out/vs/workbench/api/node/extensionHostProcess.js:124:6205)
	at async w.m (/home/username/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/out/vs/workbench/api/node/extensionHostProcess.js:124:6168)
	at async w.l (/home/username/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/out/vs/workbench/api/node/extensionHostProcess.js:124:5625)
```

### Terraform Configuration

This is the added conf for hashicorp.terraform in the vscode `settings.json` :
```json
    "[terraform]": {
        "editor.defaultFormatter": "hashicorp.terraform",
    },
```

I tried to add this but it appear "greyed-out" and does nothing:
```json
    "terraform.languageServer.terraform.path":"/home/username/.local/bin/terraform",
```
same for `terraform.languageServer.path`
Also tried various versions including 2.24.0 (https://github.com/hashicorp/vscode-terraform/blob/main/CHANGELOG.md#2240-2022-08-23) where the settings had been renamed.

### Anything Else?

What am I not seeing ?

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by thenger** [comment]
eh
ok. thank you for your quick response !

It appears that I had tested some stuffs and ended up modifying the "Remote JSON settings" (without noticing) and added the following :
```json
 "terraform.languageServer.path": "~/.local/bin/terraform",
```
and either because it's not the `terraform-ls` bin or because `~` is not expanded (but I think it's the later)
it was never going to work

now my config works : I removed every config related to hashicorp and works as I expected

Sorry for the time loss and thanks again

**Comment by radeksimko** [comment]
Glad it got resolved.
