### ISSUE TITLE
1.40 Language server crashes after enabling 

### ISSUE THREAD

**Issue by mattbowes** [hashicorp/vscode-terraform#210]
VSCode 1.37.1 on Windows 10
The extentinon has been updated to 1.40
ran the command Terrafrom: Enable/Disable Language Server
Language server crashes every time I hover over a resource

 2019/08/26 12:13:54 Server started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x8d6493]

goroutine 54 [running]:
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc0002b0960, 0xc000528308, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:184 +0x123
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(0xc0002b0960, 0xc000528308, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:160 +0x66
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0002b0960, 0x11bd480, 0xc0003e5180, 0x11be080, 0x1948390, 0xeef5a0, 0xc0000f9800, 0xff32e6, 0x8, 0xc0003f4f20, ...)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:87 +0xa7
main.TextDocumentHover(0x11bcd80, 0xc00038a0f0, 0xc000096000, 0x3d, 0x260, 0x2d, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:549 +0x299
reflect.Value.call(0xea4ae0, 0x1037d68, 0x13, 0xfee7d0, 0x4, 0xc00038a120, 0x2, 0x2, 0xc000062e00, 0xc00009fdc8, ...)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xea4ae0, 0x1037d68, 0x13, 0xc00038a120, 0x2, 0x2, 0xe49040, 0xc00038a120, 0x1)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc00038a120, 0x2, 0x2, 0x1, 0xc000004120, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11bcd80, 0xc00038a0f0, 0xc000079ac0, 0xc000079f30, 0xc000473ee8, 0x10, 0xc000473ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc0002058a0, 0x11bcd80, 0xc00038a0f0, 0xc000079ac0, 0x0, 0x0, 0x11bcd80, 0xc00038a0f0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c63c0, 0x11bccc0, 0xc000532500, 0x11b2120, 0xc0002058a0, 0xc000079ac0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc00044c650, 0xc0000c63c0, 0xc0003746c0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141
[Info  - 12:14:24 PM] Connection to server got closed. Server will restart.
[Error - 12:14:24 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
	at Pipe.asyncWrap (C:\Users\user\.vscode\extensions\ms-azuretools.vscode-azureterraform-0.2.4\node_modules\async-listener\glue.js:188:31)
2019/08/26 12:14:24 Server started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x8d6493]

goroutine 25 [running]:
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc00053a870, 0xc000528330, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:184 +0x123
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(0xc00053a870, 0xc000528330, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:160 +0x66
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc00053a870, 0x11bd480, 0xc0001caff0, 0x11be080, 0x1948390, 0xeef5a0, 0xc0004b9800, 0xff32e6, 0x8, 0xc0003c2f20, ...)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:87 +0xa7
main.TextDocumentHover(0x11bcd80, 0xc00035aa80, 0xc00012e000, 0x3d, 0x260, 0x35, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:549 +0x299
reflect.Value.call(0xea4ae0, 0x1037d68, 0x13, 0xfee7d0, 0x4, 0xc00035bbf0, 0x2, 0x2, 0xc000430000, 0xc000515dc8, ...)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xea4ae0, 0x1037d68, 0x13, 0xc00035bbf0, 0x2, 0x2, 0xe49040, 0xc00035bbf0, 0x1)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc00035bbf0, 0x2, 0x2, 0x1, 0xc000204280, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11bcd80, 0xc00035aa80, 0xc000490140, 0xc00021b9f0, 0xc00046bee8, 0x10, 0xc00046bee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc000205880, 0x11bcd80, 0xc00035aa80, 0xc000490140, 0x0, 0x0, 0x11bcd80, 0xc00035aa80)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c63c0, 0x11bccc0, 0xc000490100, 0x11b2120, 0xc000205880, 0xc000490140, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc00049a030, 0xc0000c63c0, 0xc000486090)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141
[Info  - 12:15:38 PM] Connection to server got closed. Server will restart.
[Error - 12:15:38 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
	at Pipe.asyncWrap (C:\Users\user\.vscode\extensions\ms-azuretools.vscode-azureterraform-0.2.4\node_modules\async-listener\glue.js:188:31)
2019/08/26 12:15:38 Server started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x8d6493]

goroutine 13 [running]:
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc000564730, 0xc0004341d0, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:184 +0x123
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(0xc000564730, 0xc0004341d0, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:160 +0x66
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc000564730, 0x11bd480, 0xc0001def50, 0x11be080, 0x1948390, 0xeef5a0, 0xc0000f9800, 0xff32e6, 0x8, 0xc00051d550, ...)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:87 +0xa7
main.TextDocumentHover(0x11bcd80, 0xc000548150, 0xc000470200, 0x3d, 0x260, 0x32, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:549 +0x299
reflect.Value.call(0xea4ae0, 0x1037d68, 0x13, 0xfee7d0, 0x4, 0xc000548210, 0x2, 0x2, 0x192d1a0, 0xc0000a3dc8, ...)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xea4ae0, 0x1037d68, 0x13, 0xc000548210, 0x2, 0x2, 0xe49040, 0xc000548210, 0x1)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc000548210, 0x2, 0x2, 0x1, 0xc000440680, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11bcd80, 0xc000548150, 0xc000079d40, 0xc000079b70, 0xc00009dee8, 0x10, 0xc00009dee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc0002e02e0, 0x11bcd80, 0xc000548150, 0xc000079d40, 0x0, 0x0, 0x11bcd80, 0xc000548150)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c6000, 0x11bccc0, 0xc000079d00, 0x11b2120, 0xc0002e02e0, 0xc000079d40, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc00007d010, 0xc0000c6000, 0xc00047e1b0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141
[Info  - 12:15:38 PM] Connection to server got closed. Server will restart.
[Error - 12:15:38 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
	at Pipe.asyncWrap (C:\Users\user\.vscode\extensions\ms-azuretools.vscode-azureterraform-0.2.4\node_modules\async-listener\glue.js:188:31)
2019/08/26 12:15:38 Server started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x8d6493]

goroutine 7 [running]:
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc0004c47d0, 0xc0000061e8, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:184 +0x123
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(0xc0004c47d0, 0xc0000061e8, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:160 +0x66
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0004c47d0, 0x11bd480, 0xc0003fcff0, 0x11be080, 0x1948390, 0xeef5a0, 0xc0000f9800, 0xff32e6, 0x8, 0xc000528dc0, ...)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:87 +0xa7
main.TextDocumentHover(0x11bcd80, 0xc00017e570, 0xc000474040, 0x3d, 0x260, 0x2d, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:549 +0x299
reflect.Value.call(0xea4ae0, 0x1037d68, 0x13, 0xfee7d0, 0x4, 0xc00017e750, 0x2, 0x2, 0x192d1a0, 0xc00009bdc8, ...)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xea4ae0, 0x1037d68, 0x13, 0xc00017e750, 0x2, 0x2, 0xe49040, 0xc00017e750, 0x1)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc00017e750, 0x2, 0x2, 0x1, 0xc000204d20, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11bcd80, 0xc00017e570, 0xc00021c200, 0xc00021c130, 0xc000195ee8, 0x10, 0xc000195ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc000204440, 0x11bcd80, 0xc00017e570, 0xc00021c200, 0x0, 0x0, 0x11bcd80, 0xc00017e570)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc0000c6000, 0x11bccc0, 0xc00021c1c0, 0x11b2120, 0xc000204440, 0xc00021c200, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc0003840a0, 0xc0000c6000, 0xc0002ea090)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141
[Info  - 12:15:42 PM] Connection to server got closed. Server will restart.
[Error - 12:15:42 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
	at Pipe.asyncWrap (C:\Users\user\.vscode\extensions\ms-azuretools.vscode-azureterraform-0.2.4\node_modules\async-listener\glue.js:188:31)
2019/08/26 12:15:42 Server started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x8d6493]

goroutine 28 [running]:
github.com/hashicorp/terraform/lang.(*Scope).evalContext(0xc0005747d0, 0xc00043a190, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:184 +0x123
github.com/hashicorp/terraform/lang.(*Scope).EvalContext(0xc0005747d0, 0xc00043a190, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:160 +0x66
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc0005747d0, 0x11bd3c0, 0xc00055e300, 0x11be080, 0x1948390, 0xeef5a0, 0xc000443800, 0xff32e6, 0x8, 0xc000550e70, ...)
	/home/travis/gopath/pkg/mod/github.com/hashicorp/terraform@v0.12.5/lang/eval.go:87 +0xa7
main.TextDocumentHover(0x11bcd80, 0xc00038ee40, 0xc00054c140, 0x3d, 0x23c, 0x23, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/juliosueiras/terraform-lsp/main.go:549 +0x299
reflect.Value.call(0xea4ae0, 0x1037d68, 0x13, 0xfee7d0, 0x4, 0xc00038ef00, 0x2, 0x2, 0xc000506380, 0xc000197dc8, ...)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:447 +0x45b
reflect.Value.Call(0xea4ae0, 0x1037d68, 0x13, 0xc00038ef00, 0x2, 0x2, 0xe49040, 0xc00038ef00, 0x1)
	/home/travis/.gimme/versions/go1.11.12.linux.amd64/src/reflect/value.go:308 +0xab
reflect.Value.Call-fm(0xc00038ef00, 0x2, 0x2, 0x1, 0xc0002e46a0, 0x1)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:211 +0x67
github.com/creachadair/jrpc2/handler.newHandler.func7(0x11bcd80, 0xc00038ee40, 0xc00021a240, 0xc0002e2070, 0xc0004b5ee8, 0x10, 0xc0004b5ee0)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:222 +0x232
github.com/creachadair/jrpc2/handler.Func.Handle(0xc00050c240, 0x11bcd80, 0xc00038ee40, 0xc00021a240, 0x0, 0x0, 0x11bcd80, 0xc00038ee40)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/handler/handler.go:23 +0x4b
github.com/creachadair/jrpc2.(*Server).invoke(0xc00051e000, 0x11bccc0, 0xc0002e20c0, 0x11b2120, 0xc00050c240, 0xc00021a240, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:294 +0x1b7
github.com/creachadair/jrpc2.(*Server).dispatch.func1(0xc00007c0e0, 0xc00051e000, 0xc000376510)
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:185 +0x108
created by github.com/creachadair/jrpc2.(*Server).dispatch
	/home/travis/gopath/pkg/mod/github.com/creachadair/jrpc2@v0.1.2/server.go:183 +0x141
[Error - 12:15:46 PM] Connection to server got closed. Server will not be restarted.
[Error - 12:15:46 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2153:42)
	at LanguageClient.handleConnectionClosed (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\main.js:151:15)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-languageclient\lib\client.js:2140:18)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at StreamMessageReader.fireClose (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at Socket.listen.readable.on (C:\Users\user\.vscode\extensions\mauve.terraform-1.4.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
	at Socket.emit (events.js:187:15)
	at Pipe.Socket._destroy._handle.close (net.js:606:12)
	at Pipe.asyncWrap (C:\Users\user\.vscode\extensions\ms-azuretools.vscode-azureterraform-0.2.4\node_modules\async-listener\glue.js:188:31)

**Comment by ashemedai** [comment]
Best to report these in the https://github.com/juliosueiras/terraform-lsp project.

I am running 0.0.9 and haven't had crashes yet. Do you still get these with that version?

**Comment by mendhak** [comment]
Future searchers, see here:  https://github.com/juliosueiras/terraform-lsp/issues/16

**Comment by paultyng** [comment]
We just released [v2.0.0-rc.1](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) of the extension. The main features include:

* Added syntax support for 0.12
* Added [terraform-ls](https://github.com/hashicorp/terraform-ls) usage by default (currently on 0.3.0, which offers basic provider code completion)

You can find additional information and specifics in the [release notes](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.0.0-rc.1) and [CHANGELOG](https://github.com/hashicorp/vscode-terraform/blob/master/CHANGELOG.md).

With this release we expect that many of the prior issues and PRs are no longer relevant or have been addressed, and are therefore being closed. If you feel the action taken on an issue or PR is in error, please comment as such and we can figure out the appropriate way to address it.

We plan to add the final 2.0.0 release to the marketplace soon, but are actively seeking your feedback now on the release candidates. You can download the .vsix from the releases page and [manually install it in VS Code](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) to try it out.
