### ISSUE TITLE
Terraform Extension Install Issue

### ISSUE THREAD

**Issue by kclinden** [hashicorp/vscode-terraform#409]
I am getting the following error when trying to get the terraform extension to work.
I don't have any terraform settings in my extensions settings file. 

```
  ERR Unable to write to User Settings because terraform.languageServer.external is not a registered configuration.: Error: Unable to write to User Settings because terraform.languageServer.external is not a registered configuration.
    at e.reject (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5363:839)
    at e.resolveAndValidate (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5366:717)
    at e.doWriteConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5361:70)
    at Object.factory (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5360:801)
    at u.consume (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:130:75)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:129:886
    at new Promise (<anonymous>)
    at u.queue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:129:810)
    at e.writeConfiguration (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5360:786)
    at C.writeConfigurationValue (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5389:83)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5377:320
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by kclinden** [comment]
Additional errors found on a clean install of vscode.

```
URI "" is not valid
```

```
[Extension Host] stack trace: Error: URI "" is not valid	at handleResponse (/Users/kclinden/.vscode/extensions/hashicorp.terraform-2.0.1/node_modules/vscode-jsonrpc/lib/main.js:436:48)	at processMessageQueue (/Users/kclinden/.vscode/extensions/hashicorp.terraform-2.0.1/node_modules/vscode-jsonrpc/lib/main.js:263:17)	at Immediate.<anonymous> (/Users/kclinden/.vscode/extensions/hashicorp.terraform-2.0.1/node_modules/vscode-jsonrpc/lib/main.js:247:13)	at processImmediate (internal/timers.js:439:21)
```
