### ISSUE TITLE
Document link broken?

### ISSUE THREAD

**Issue by bnm22** [hashicorp/vscode-terraform#537]
The resource document link in the extension no longer works after the 2.x.x upgrade. Is this intentional?

**Comment by sca-ai** [comment]
i've got the same problem on: 
- vs-code current, 
- vs-code plugin hashicorp.terraform v2.5.0, 
- terraform v0.14.5 on 
- win10.

here's the respective log of language server `terraform-ls`:
```
[2021-01-24 15:25:26.351] [exthost] [error] [hashicorp.terraform] provider FAILED
[2021-01-24 15:25:26.351] [exthost] [error] Error: no such method "textDocument/documentLink"
	at handleResponse (c:\Users\{removed}\.vscode\extensions\hashicorp.terraform-2.5.0\node_modules\vscode-jsonrpc\lib\common\connection.js:477:48)
	at processMessageQueue (c:\Users\{removed}\.vscode\extensions\hashicorp.terraform-2.5.0\node_modules\vscode-jsonrpc\lib\common\connection.js:292:17)
	at Immediate.<anonymous> (c:\Users\{removed}\.vscode\extensions\hashicorp.terraform-2.5.0\node_modules\vscode-jsonrpc\lib\common\connection.js:276:13)
	at processImmediate (internal/timers.js:439:21)
	at process.topLevelDomainCallback (domain.js:130:23)
```

**Comment by marrobi** [comment]
Similar issue here:
```
2021/02/03 10:11:27 server.go:568: Received 1 new requests
2021/02/03 10:11:27 server.go:174: Processing 1 requests
2021/02/03 10:11:27 server.go:265: Checking request for "textDocument/documentLink": {"textDocument":{"uri":"file:///pathto/terraformfile.tf"}}
2021/02/03 10:11:27 server.go:293: Task error: [-32601] no such method "textDocument/documentLink"
2021/02/03 10:11:27 rpc_logger.go:45: Error for "textDocument/documentLink" (ID 53): [-32601] no such method "textDocument/documentLink"
2021/02/03 10:11:27 server.go:246: Completed 1 requests [140.4µs elapsed]
[Error - 10:11:27 AM] Request textDocument/documentLink failed.
  Message: no such method "textDocument/documentLink"
  Code: -32601 
  ```

**Comment by radeksimko** [comment]
Hi folks,
Document links were (re)introduced to the language server in the most recent version (0.14.0) released today. The extension should download it and prompt installation automatically on the next launch.

Initially this includes just links to provider docs as per https://github.com/hashicorp/terraform-ls/pull/402 
Resource and data source links are tracked under https://github.com/hashicorp/terraform-ls/issues/190 and core documentation under https://github.com/hashicorp/terraform-ls/issues/418

Generally this functionality will continue to be maintained on the language server side, so I would recommend subscribing to these issues there, and/or file any relevant bugs you find over there in that repo, rather than here.

Thanks.
