### ISSUE TITLE
Permission denied on installing terraform-ls

### ISSUE THREAD

**Issue by bkonicekprivo** [hashicorp/vscode-terraform#695]
Since today (this was working fine on 7/15) I cannot get terraform-ls to work in my Ubuntu 20.04 WSL2 instance of VSCode.

Running the command pallette command for "Terraform: Enable Language Server" returns the error `"Running the contributed command: 'terraform.enableLanguageServer' failed.`

In the Remote Extension Host output console I see the following messages whenever I try to enable it.

```
[2021-07-19 13:36:02.958] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
[2021-07-19 13:36:02.958] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/bkonicek/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/emmet/dist/node/emmetNodeMain
[2021-07-19 13:36:02.974] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
[2021-07-19 13:36:02.974] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/bkonicek/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/merge-conflict/dist/mergeConflictMain
[2021-07-19 13:36:02.979] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
[2021-07-19 13:36:02.979] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/bkonicek/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/extensions/testing-editor-contributions/dist/extension.js
[2021-07-19 13:36:02.980] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2021-07-19 13:36:02.980] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/bkonicek/.vscode-server/extensions/eamodio.gitlens-11.6.0/dist/gitlens
[2021-07-19 13:36:03.136] [exthost] [info] eager extensions activated
[2021-07-19 13:39:33.061] [exthost] [error] Error: EACCES: permission denied, access '/home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/lsp/terraform-ls'
	at Object.accessSync (fs.js:220:3)
	at /home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/out/languageServerInstaller.js:128:12
	at Generator.next (<anonymous>)
	at /home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/out/languageServerInstaller.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/out/languageServerInstaller.js:4:12)
	at getLsVersion (/home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/out/languageServerInstaller.js:126:12)
	at LanguageServerInstaller.<anonymous> (/home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/out/languageServerInstaller.js:39:42)
	at Generator.next (<anonymous>)
	at fulfilled (/home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/out/languageServerInstaller.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) terraform.enableLanguageServer
```

It looks like the permissions are somehow wrong, but I'm not sure how that would have happened.

```
bkonicek@PRI-XPS13-BK:~/git/Projects/arcbio$ ls -la /home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/lsp/terraform-ls
-rw-r--r-- 1 bkonicek bkonicek 108520 Jul 15 19:01 /home/bkonicek/.vscode-server/extensions/hashicorp.terraform-2.13.2/lsp/terraform-ls
```

I have tried uninstalling and re-installing the Terraform extension.

This is working just fine in a non-WSL VSCode window.

VSCode Version: 1.58.2
Terraform extension version: 2.13.2
Windows 10 20H2 (19042.1110)

**Comment by bkonicekprivo** [comment]
I downgrade my Terraform extension to 2.13.1 and terraform-ls was able to update and worked again. Upgrading it back up to 2.13.2 broke it again.

**Comment by radeksimko** [comment]
I am not sure how that change between `2.13.1` / `2.13.2` would cause this particular problem.

It should only affect periodic updates from 24hrs after VS Code launch onwards - which in `2.13.1` were completely broken (on all platforms) and fixed in `2.13.2`. The update process itself was however unchanged.

I never tried the extension on Windows with WSL and I am unsure what is so specific about the filesystem that would trigger this particular permission error, but I can fire up a Windows VM and try reproducing it.

**Comment by bkonicekprivo** [comment]
Thanks, @radeksimko - I just noticed that my extension auto-updated to `2.14.0` and the language server is working again.

**Comment by radeksimko** [comment]
Great, I'm going to close this issue then but feel free to open a new one if the problem resurfaces.
