### ISSUE TITLE
Extension not working on WSL

### ISSUE THREAD

**Issue by JakubKoralewski** [hashicorp/vscode-terraform#716]
Language server seems to not be working on WSL.

### What doesn't work
1. Running commands through the command palette always immediately fails.
	
	For example, running Terraform: init through the command palette fails:
	```
	[2021-08-04 13:16:04.792] [exthost] [error] TypeError: Cannot read property 'commandPrefix' of undefined
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:78:60
	at Generator.next (<anonymous>)
	at fulfilled (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:93:5) terraform.init
	```
	But it works in the terminal.

	Terraform: validate
	```
	[2021-08-04 13:20:57.646] [exthost] [error] TypeError: Cannot read property 'commandPrefix' of undefined
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:192:60
	at Generator.next (<anonymous>)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:4:12)
	at modulesCallersCommand (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:191:12)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:198:32
	at Generator.next (<anonymous>)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:4:12)
	at moduleCallers (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:197:12)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:209:36
	at Generator.next (<anonymous>)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:4:12)
	at terraformCommand (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:204:12)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:86:19
	at Generator.next (<anonymous>)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:4:12)
	at /home/jcubed/.vscode-server/extensions/hashicorp.terraform-2.14.0/out/extension.js:85:74
	at S._executeContributedCommand (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:84:120585)
	at S.$executeContributedCommand (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:84:121023)
	at c._doInvokeHandler (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:88:12743)
	at c._invokeHandler (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:88:12435)
	at c._receiveRequest (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:88:11097)
	at c._receiveOneMessage (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:88:9900)
	at /home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:88:8004
	at d.fire (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at h.fire (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:65:15777)
	at /home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:103:29836
	at d.fire (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at h.fire (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:65:15777)
	at r._receiveMessage (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:65:21035)
	at /home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:65:17921
	at d.fire (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at u.acceptChunk (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:65:13138)
	at /home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:65:12486
	at d.fire (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:57:1726)
	at b._acceptChunk (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:103:19103)
	at /home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:103:15516
	at Socket._ (/home/jcubed/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/out/vs/server/remoteExtensionHostProcess.js:103:13107)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at TCP.onStreamRead (internal/stream_base_commons.js:188:23) terraform.validate
	```

	Similar for all the rest.

2. Syntax errors are not reported.
3. Code completion/suggestion not working.

### What works
1. Syntax highlighting works.
2. Snippets, like `fore` etc. work

Tested both opening the folder in WSL's filesystem and Windows' file system. Both through WSL.
Works fine through Windows, despite not even having Terraform installed on Windows 😅 

EDIT: I uninstalled the extension and now can't install it back on WSL for some reason...

**Comment by JakubKoralewski** [comment]
I managed to finally reinstall and it seems to be working now. I have no idea what's going on. Feel free to close, I'll let you know when it comes back.
